### PR TITLE
Modification so that rosetta can run independent of any Django project but still translate it.

### PR DESCRIPTION
**Pull request by jyoost**
### this integrates poedit mass translations.  and allows you to run the test project in this project to translate ANY Django project.  It will hunt for and find and set the LOCALE_DIRS settings by setting TRANSLATE_PROJECT_PATH. If you want to merge this into the main branch I can further document.

Modification so that rosetta can run independent of any Django project but still translate it.

added ability to get a list of "locale"
directory (LOCALE_DIRS) from the project by
setting TRANSLATE_PROJECT_PATH to the
Django project you want to translate.

Added the ability to execute poedit from the
list screen my clicking on the file name
which I made a link.

You must set PATH_TO_POEDIT to the full path
of poedit.

I did all this because I could not get DEEPL
to work correctly, and poedit will machine
"pretranslate" a whole po file :)

### All Submissions:

- [ ] Are tests passing? (From the root-level of the repository please run `pip install tox && tox`)
- [ ] I have added or updated a test to cover the changes proposed in this Pull Request
- [ ] I have updated the documentation to cover the changes proposed in this Pull Request

### CODE REVIEW

**Comment by chenluyong** [comment]
Your coding habits are very good, but submitting these to PR is a very troublesome thing.

**Comment by jyoost** [comment]
Why do you say that?

**Comment by jyoost** [comment]
You can get this on my fork.

**Comment by chenluyong** [comment]
Convert `'` to `"` will not help your `PR`, but it will affect many irrelevant code files.

**Comment by jyoost** [comment]
Understand, I did not even realize. I think Black did it.

**Pull request closed without merging**
