### PR TITLE
Rosetta at admin panel

### PR DESCRIPTION
**Pull request by scream4ik**
For enable rosetta ad admin panel we need:
1. Add ROSETTA_SHOW_AT_ADMIN_PANEL = True to settings.py
2. Rosetta need to be first at INSTALLED_APPS

### CODE REVIEW

**Comment by mbi** [comment]
Thanks for this pull request. Would you please also update [docs/settings.rst](../blob/develop/docs/settings.rst) explaining what this does?

**Comment by mbi** [comment]
Okay, I kind of like this idea, but when I first tested it I overlooked that I need to have `rosetta` in first position in `INSTALLED_APPS`, so all my other apps disappeared from the admin. I don't suppose there is a way to address this so that it works even if this is not the case?

Another, simpler, way of achieving the same effect would be to provide a replacement for `admin/index.html` and have the user add a couple lines to their urls.py:

    admin.autodiscover()
    admin.site.index_template = 'rosetta/admin_index.html'

What do you think?

**Comment by mbi** [comment]
Okay, done, this works much better now. Do you mind checking out `pr/176` and give it a try?

**Comment by scream4ik** [comment]
I rechecked. Works fine.
I agree with you. Your way more graceful

**Comment by mbi** [comment]
Okay, thank you, merged!

**Pull request merged**
