### PR TITLE
added stats by symbols on 'list_languages' page

### PR DESCRIPTION
**Pull request by tsouvarev**
In our company we needed statistics by symbols to measure translators work. So, I changed first page a bit to show how many symbols in messages, translated symbols, symbols in translations and overall progress by symbols

### CODE REVIEW

**Comment by mbi** [comment]
Thank you for your contribution. I'm not against more stats, but my concern with this pull request is that changes were made in `polib`, which I'm shipping with Rosetta, but is an external dependency: when I'll update `polib` I'll have to maintain your changes in that file, too.

Would you mind suggesting `polib` to include your statistics?
https://bitbucket.org/izi/polib/wiki/Home

Alternatively maybe we could remove the added methods from `polib`, and have them live in `poutil.py`?

**Comment by tsouvarev** [comment]
Well, that was unexpected. Why would you do that, keeping in mind future updates of `polib`? 
Anyway, I certainly can make pull-request in `polib`

**Comment by mbi** [comment]
Well I'm following development of polib, and to always make sure the version shipped with Rosetta is 100% tested and supported, it's easier to plainly include the unique file, rather than declaring it as an external dependency and have it pulled at installation.

**Comment by mbi** [comment]
Wondering, was your PR accepted in polib?

**Pull request closed without merging**
