### PR TITLE
Patch for issue #135

### PR DESCRIPTION
**Pull request by pgcd**
Here's my working implementation to give some basic information to users when something goes wrong when saving a file.

### CODE REVIEW

**Comment by mbi** [comment]
Looks good, any chance you could contribute a test that displays a message?

**Comment by pgcd** [comment]
I would love to but I won't be able to until next week - no access to a
real workplace right now. Could that work?

**Comment by mbi** [comment]
Merged, thank you!

**Comment by pgcd** [comment]
Thank you - sorry I couldn't get to the "preparing the test" part =)

**Pull request merged**
