### PR TITLE
Accept languages as 'fr_FR.utf8' in lang_sel url

### PR DESCRIPTION
**Pull request by strycore**
I have modified the urlconf to allow language codes with dots and underscores (as in fr_FR.utf8)

### CODE REVIEW

**Comment by mbi** [comment]
This calls for a test, please?

**Comment by strycore** [comment]
Hope this is ok, tell me if you want more specific test cases.

**Comment by mbi** [comment]
Thanks, this is a good start. I'll just add another test to make sure a po file is actually loaded and displayed and merge this.

Cheers.

**Comment by mbi** [comment]
Merged, thank you!

**Pull request merged**
