### PR TITLE
Make MO file compilation optional, issue #155

### PR DESCRIPTION
**Pull request by nealtodd**
### All Submissions:
- [x] Are tests passing? (From the root-level of the repository please run `pip install tox && tox`)
- [x] I have added or updated a test to cover the changes proposed in this Pull Request
- [x] I have updated the documentation to cover the changes proposed in this Pull Request

Implements #155

### CODE REVIEW

**Comment by mbi** [comment]
Fantastic, thank you!

**Comment by nealtodd** [comment]
Thanks for the merge @mbi !

Do you have a rough release date for 0.7.11 to PyPI?

No rush, as I understand you may have other features/updates you want to put in it (just wondering so I know when to move my project off my Rosetta fork and back onto PyPI in the requirements.txt).

**Comment by mbi** [comment]
Cheers. I usually push to PyPI whenever we have a few interesting features to release. I suppose now would be perfectly fine. Will do so when I get a chance today.

**Comment by mbi** [comment]
Alright pushed! I usually screw up PyPI released in a way or another, let's hope this one will stick :)

**Comment by nealtodd** [comment]
Fantastic, thanks Marco! Downloaded 0.7.11 from PyPI, all looks good to me, ta.

**Pull request merged**
